server {
    listen 80;
    server_name localhost;

    # Ficheros estáticos del frontend Vue
    root /usr/share/nginx/html;
    index index.html;

    # Vue Router — todas las rutas no encontradas van al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy REST → backend FastAPI
    location /api/ {
        proxy_pass         http://backend:8000/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 120s;
    }

    # Proxy WebSocket → backend FastAPI (Suricata live feed)
    location /api/suricata/ws/ {
        proxy_pass         http://backend:8000/api/suricata/ws/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
        proxy_read_timeout 3600s;
    }
}
